language: php

php:
    - 5.4

before_script: 
    - composer install -n
    - npm install
    - php app/console server:run &
    - ./node_modules/.bin/phantomjs --webdriver=8643 &

script: 
    - ./bin/behat --format=progress
